name: "Nightly build"

on:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
    nightly-build:
      uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
      with:
        nightly: true
        os: '["ubuntu-latest"]'
      secrets: inherit
