# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
    nightly-build:
      uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.5.9
      with:
        nightly: true
        os: '["ubuntu-latest"]'
        extraCommand: mvn install:install-file -Dfile=lib/vertica-jdbc-7.1.0-0.jar -DgroupId=vertica-jdbc -DartifactId=com.vertica -Dversion=7.1.0 -Dpackaging=jar
      secrets: inherit
