name: Build and Test

permissions:
  contents: read
  pull-requests: write
  packages: read
  id-token: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    secrets: inherit
    with:
      os: '["ubuntu-latest"]'
