name: Build and Test

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build-test:
    needs: authorize
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.6.5
    secrets: inherit
    with:
      os: '["ubuntu-latest"]'
      extraCommand: mvn install:install-file -Dfile=lib/vertica-jdbc-7.1.0-0.jar -DgroupId=vertica-jdbc -DartifactId=com.vertica -Dversion=7.1.0 -Dpackaging=jar
    
  integration-tests:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        java: [11, 17, 21]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Test With Maven
        run: mvn clean verify --file pom.xml

  dependabot:
    needs: build-test
    uses: liquibase/build-logic/.github/workflows/dependabot-automerge.yml@v0.6.5
    secrets: inherit
